/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "var(--container-padding)",
      screens: {
        "2xl": "var(--container-max-width)",
      },
    },
    extend: {
      fontFamily: {
        sans: "var(--font-sans)",
        display: "var(--font-display)",
        mono: "var(--font-mono)",
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        '2xl': "var(--text-2xl)",
        '3xl': "var(--text-3xl)",
        '4xl': "var(--text-4xl)",
        '5xl': "var(--text-5xl)",
        '6xl': "var(--text-6xl)",
        '7xl': "var(--text-7xl)",
        '8xl': "var(--text-8xl)",
        '9xl': "var(--text-9xl)",
      },
      lineHeight: {
        none: "var(--leading-none)",
        tight: "var(--leading-tight)",
        snug: "var(--leading-snug)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
        loose: "var(--leading-loose)",
      },
      fontWeight: {
        thin: "var(--font-thin)",
        extralight: "var(--font-extralight)",
        light: "var(--font-light)",
        normal: "var(--font-normal)",
        medium: "var(--font-medium)",
        semibold: "var(--font-semibold)",
        bold: "var(--font-bold)",
        extrabold: "var(--font-extrabold)",
        black: "var(--font-black)",
      },
      spacing: {
        'phi-xs': "var(--space-phi-xs)",
        'phi-sm': "var(--space-phi-sm)",
        'phi-base': "var(--space-phi-base)",
        'phi-md': "var(--space-phi-md)",
        'phi-lg': "var(--space-phi-lg)",
        'phi-xl': "var(--space-phi-xl)",
        'phi-2xl': "var(--space-phi-2xl)",
        'phi-3xl': "var(--space-phi-3xl)",
        'phi-4xl': "var(--space-phi-4xl)",
      },
      colors: {
        border: "hsl(var(--color-border))",
        input: "hsl(var(--color-input))",
        ring: "hsl(var(--color-ring))",
        background: "hsl(var(--color-background))",
        foreground: "hsl(var(--color-foreground))",
        primary: {
          50: "hsl(var(--color-primary-50))",
          100: "hsl(var(--color-primary-100))",
          200: "hsl(var(--color-primary-200))",
          300: "hsl(var(--color-primary-300))",
          400: "hsl(var(--color-primary-400))",
          DEFAULT: "hsl(var(--color-primary))",
          500: "hsl(var(--color-primary))",
          600: "hsl(var(--color-primary-600))",
          700: "hsl(var(--color-primary-700))",
          800: "hsl(var(--color-primary-800))",
          900: "hsl(var(--color-primary-900))",
          foreground: "hsl(var(--color-primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--color-secondary))",
          foreground: "hsl(var(--color-secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--color-destructive))",
          foreground: "hsl(var(--color-destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--color-muted))",
          foreground: "hsl(var(--color-muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--color-accent))",
          foreground: "hsl(var(--color-accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--color-popover))",
          foreground: "hsl(var(--color-popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--color-card))",
          foreground: "hsl(var(--color-card-foreground))",
        },
        success: "hsl(var(--color-success))",
        warning: "hsl(var(--color-warning))",
        
        // Bone & Banana Pudding Light Theme Colors
        bone: {
          50: "hsl(var(--bone-50))",
          100: "hsl(var(--bone-100))",
          200: "hsl(var(--bone-200))",
          300: "hsl(var(--bone-300))",
          400: "hsl(var(--bone-400))",
          500: "hsl(var(--bone-500))",
          600: "hsl(var(--bone-600))",
          700: "hsl(var(--bone-700))",
          800: "hsl(var(--bone-800))",
          900: "hsl(var(--bone-900))",
          950: "hsl(var(--bone-950))",
        },
        pudding: {
          50: "hsl(var(--pudding-50))",
          100: "hsl(var(--pudding-100))",
          200: "hsl(var(--pudding-200))",
          300: "hsl(var(--pudding-300))",
          400: "hsl(var(--pudding-400))",
          500: "hsl(var(--pudding-500))",
          600: "hsl(var(--pudding-600))",
          700: "hsl(var(--pudding-700))",
          800: "hsl(var(--pudding-800))",
          900: "hsl(var(--pudding-900))",
          950: "hsl(var(--pudding-950))",
        },
        caramel: "hsl(var(--caramel))",
        vanilla: "hsl(var(--vanilla))",
        cream: "hsl(var(--cream))",
        toast: "hsl(var(--toast))",
        honey: "hsl(var(--honey))",
        
        // Surface colors for sidebar and navbar
        sidebar: "hsl(var(--color-sidebar))",
        "sidebar-foreground": "hsl(var(--color-sidebar-foreground))",
        navbar: "hsl(var(--color-navbar))",
        "navbar-foreground": "hsl(var(--color-navbar-foreground))",
        
        // Dark elements for light mode
        chip: "hsl(var(--color-chip))",
        "chip-foreground": "hsl(var(--color-chip-foreground))",
        badge: "hsl(var(--color-badge))",
        "badge-foreground": "hsl(var(--color-badge-foreground))",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-base)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        '2xl': "var(--radius-2xl)",
        '3xl': "var(--radius-3xl)",
        full: "var(--radius-full)",
      },
      gap: {
        'phi-xs': "var(--space-phi-xs)",
        'phi-sm': "var(--space-phi-sm)",
        'phi-base': "var(--space-phi-base)",
        'phi-md': "var(--space-phi-md)",
        'phi-lg': "var(--space-phi-lg)",
        'phi-xl': "var(--space-phi-xl)",
        'phi-2xl': "var(--space-phi-2xl)",
      },
      zIndex: {
        'behind': "var(--z-behind)",
        '10': "var(--z-10)",
        '20': "var(--z-20)",
        '30': "var(--z-30)",
        '40': "var(--z-40)",
        '50': "var(--z-50)",
        'modal': "var(--z-modal)",
        'popover': "var(--z-popover)",
        'tooltip': "var(--z-tooltip)",
        'toast': "var(--z-toast)",
        'max': "var(--z-max)",
      },
      transitionDuration: {
        'fast': "var(--duration-fast)",
        'normal': "var(--duration-normal)",
        'slow': "var(--duration-slow)",
      },
      transitionTimingFunction: {
        'linear': "var(--ease-linear)",
        'in': "var(--ease-in)",
        'out': "var(--ease-out)",
        'in-out': "var(--ease-in-out)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}