/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "var(--container-padding)",
      screens: {
        "2xl": "var(--container-max-width)",
      },
    },
    extend: {
      fontFamily: {
        sans: "var(--font-sans)",
        display: "var(--font-display)",
        mono: "var(--font-mono)",
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        '2xl': "var(--text-2xl)",
        '3xl': "var(--text-3xl)",
        '4xl': "var(--text-4xl)",
        '5xl': "var(--text-5xl)",
        '6xl': "var(--text-6xl)",
        '7xl': "var(--text-7xl)",
        '8xl': "var(--text-8xl)",
        '9xl': "var(--text-9xl)",
      },
      lineHeight: {
        none: "var(--leading-none)",
        tight: "var(--leading-tight)",
        snug: "var(--leading-snug)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
        loose: "var(--leading-loose)",
      },
      fontWeight: {
        thin: "var(--font-thin)",
        extralight: "var(--font-extralight)",
        light: "var(--font-light)",
        normal: "var(--font-normal)",
        medium: "var(--font-medium)",
        semibold: "var(--font-semibold)",
        bold: "var(--font-bold)",
        extrabold: "var(--font-extrabold)",
        black: "var(--font-black)",
      },
      spacing: {
        'phi-xs': "var(--space-phi-xs)",
        'phi-sm': "var(--space-phi-sm)",
        'phi-base': "var(--space-phi-base)",
        'phi-md': "var(--space-phi-md)",
        'phi-lg': "var(--space-phi-lg)",
        'phi-xl': "var(--space-phi-xl)",
        'phi-2xl': "var(--space-phi-2xl)",
        'phi-3xl': "var(--space-phi-3xl)",
        'phi-4xl': "var(--space-phi-4xl)",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          50: "hsl(var(--color-primary-50))",
          100: "hsl(var(--color-primary-100))",
          200: "hsl(var(--color-primary-200))",
          300: "hsl(var(--color-primary-300))",
          400: "hsl(var(--color-primary-400))",
          DEFAULT: "hsl(var(--primary))",
          500: "hsl(var(--primary))",
          600: "hsl(var(--color-primary-600))",
          700: "hsl(var(--color-primary-700))",
          800: "hsl(var(--color-primary-800))",
          900: "hsl(var(--color-primary-900))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: "hsl(var(--success))",
        warning: "hsl(var(--warning))",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-base)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        '2xl': "var(--radius-2xl)",
        '3xl': "var(--radius-3xl)",
        full: "var(--radius-full)",
      },
      gap: {
        'phi-xs': "var(--space-phi-xs)",
        'phi-sm': "var(--space-phi-sm)",
        'phi-base': "var(--space-phi-base)",
        'phi-md': "var(--space-phi-md)",
        'phi-lg': "var(--space-phi-lg)",
        'phi-xl': "var(--space-phi-xl)",
        'phi-2xl': "var(--space-phi-2xl)",
      },
      zIndex: {
        'behind': "var(--z-behind)",
        '10': "var(--z-10)",
        '20': "var(--z-20)",
        '30': "var(--z-30)",
        '40': "var(--z-40)",
        '50': "var(--z-50)",
        'modal': "var(--z-modal)",
        'popover': "var(--z-popover)",
        'tooltip': "var(--z-tooltip)",
        'toast': "var(--z-toast)",
        'max': "var(--z-max)",
      },
      transitionDuration: {
        'fast': "var(--duration-fast)",
        'normal': "var(--duration-normal)",
        'slow': "var(--duration-slow)",
      },
      transitionTimingFunction: {
        'linear': "var(--ease-linear)",
        'in': "var(--ease-in)",
        'out': "var(--ease-out)",
        'in-out': "var(--ease-in-out)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}