/// Artifact system for Chat 2.0 - OS-like workspace with LLM-generated interactive content
///
/// Artifacts are structured outputs from the LLM that appear as windows/panels in the workspace,
/// similar to Claude's Artifacts or "Imagine with Claude" feature.

/// Type of artifact that can be generated
enum ArtifactType {
  /// Code editor with syntax highlighting and execution
  code,

  /// Mermaid diagram or flowchart
  diagram,

  /// Interactive widget or mini-app
  widget,

  /// Rich text document or markdown
  document,

  /// Data visualization (chart, graph, table)
  visualization,

  /// Image or visual content
  image,

  /// HTML/Web content preview
  webPreview,
}

/// Position and size of an artifact window
class ArtifactWindowGeometry {
  final double x;
  final double y;
  final double width;
  final double height;
  final bool isMinimized;
  final bool isMaximized;

  const ArtifactWindowGeometry({
    this.x = 100,
    this.y = 100,
    this.width = 600,
    this.height = 400,
    this.isMinimized = false,
    this.isMaximized = false,
  });

  ArtifactWindowGeometry copyWith({
    double? x,
    double? y,
    double? width,
    double? height,
    bool? isMinimized,
    bool? isMaximized,
  }) {
    return ArtifactWindowGeometry(
      x: x ?? this.x,
      y: y ?? this.y,
      width: width ?? this.width,
      height: height ?? this.height,
      isMinimized: isMinimized ?? this.isMinimized,
      isMaximized: isMaximized ?? this.isMaximized,
    );
  }
}

/// An artifact generated by the LLM that can be displayed as an interactive window
class Artifact {
  /// Unique identifier for this artifact
  final String id;

  /// ID of the conversation this artifact belongs to
  final String conversationId;

  /// ID of the message that generated this artifact
  final String messageId;

  /// Type of artifact
  final ArtifactType type;

  /// Display title for the artifact window
  final String title;

  /// The actual content of the artifact
  final String content;

  /// Language for code artifacts (e.g., "dart", "python", "javascript")
  final String? language;

  /// Additional metadata (dependencies, settings, etc.)
  final Map<String, dynamic> metadata;

  /// Window geometry (position, size, state)
  final ArtifactWindowGeometry geometry;

  /// When this artifact was created
  final DateTime createdAt;

  /// When this artifact was last updated
  final DateTime updatedAt;

  /// Whether the artifact window is currently visible
  final bool isVisible;

  const Artifact({
    required this.id,
    required this.conversationId,
    required this.messageId,
    required this.type,
    required this.title,
    required this.content,
    this.language,
    this.metadata = const {},
    this.geometry = const ArtifactWindowGeometry(),
    required this.createdAt,
    required this.updatedAt,
    this.isVisible = true,
  });

  Artifact copyWith({
    String? title,
    String? content,
    String? language,
    Map<String, dynamic>? metadata,
    ArtifactWindowGeometry? geometry,
    DateTime? updatedAt,
    bool? isVisible,
  }) {
    return Artifact(
      id: id,
      conversationId: conversationId,
      messageId: messageId,
      type: type,
      title: title ?? this.title,
      content: content ?? this.content,
      language: language ?? this.language,
      metadata: metadata ?? this.metadata,
      geometry: geometry ?? this.geometry,
      createdAt: createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isVisible: isVisible ?? this.isVisible,
    );
  }

  /// Convert to JSON for persistence
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'conversationId': conversationId,
      'messageId': messageId,
      'type': type.name,
      'title': title,
      'content': content,
      'language': language,
      'metadata': metadata,
      'geometry': {
        'x': geometry.x,
        'y': geometry.y,
        'width': geometry.width,
        'height': geometry.height,
        'isMinimized': geometry.isMinimized,
        'isMaximized': geometry.isMaximized,
      },
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'isVisible': isVisible,
    };
  }

  /// Create from JSON
  factory Artifact.fromJson(Map<String, dynamic> json) {
    final geometryJson = json['geometry'] as Map<String, dynamic>?;

    return Artifact(
      id: json['id'] as String,
      conversationId: json['conversationId'] as String,
      messageId: json['messageId'] as String,
      type: ArtifactType.values.firstWhere(
        (e) => e.name == json['type'],
        orElse: () => ArtifactType.code,
      ),
      title: json['title'] as String,
      content: json['content'] as String,
      language: json['language'] as String?,
      metadata: (json['metadata'] as Map<String, dynamic>?) ?? {},
      geometry: geometryJson != null
          ? ArtifactWindowGeometry(
              x: (geometryJson['x'] as num?)?.toDouble() ?? 100,
              y: (geometryJson['y'] as num?)?.toDouble() ?? 100,
              width: (geometryJson['width'] as num?)?.toDouble() ?? 600,
              height: (geometryJson['height'] as num?)?.toDouble() ?? 400,
              isMinimized: geometryJson['isMinimized'] as bool? ?? false,
              isMaximized: geometryJson['isMaximized'] as bool? ?? false,
            )
          : const ArtifactWindowGeometry(),
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
      isVisible: json['isVisible'] as bool? ?? true,
    );
  }
}

/// Extension to determine artifact icon
extension ArtifactTypeIcon on ArtifactType {
  String get icon {
    switch (this) {
      case ArtifactType.code:
        return '💻';
      case ArtifactType.diagram:
        return '📊';
      case ArtifactType.widget:
        return '🎛️';
      case ArtifactType.document:
        return '📄';
      case ArtifactType.visualization:
        return '📈';
      case ArtifactType.image:
        return '🖼️';
      case ArtifactType.webPreview:
        return '🌐';
    }
  }

  String get displayName {
    switch (this) {
      case ArtifactType.code:
        return 'Code Editor';
      case ArtifactType.diagram:
        return 'Diagram';
      case ArtifactType.widget:
        return 'Widget';
      case ArtifactType.document:
        return 'Document';
      case ArtifactType.visualization:
        return 'Visualization';
      case ArtifactType.image:
        return 'Image';
      case ArtifactType.webPreview:
        return 'Web Preview';
    }
  }
}
